
package services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MLServiceService", targetNamespace = "http://services/", wsdlLocation = "http://localhost:8685/?wsdl")
public class MLServiceService
    extends Service
{

    private final static URL MLSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException MLSERVICESERVICE_EXCEPTION;
    private final static QName MLSERVICESERVICE_QNAME = new QName("http://services/", "MLServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8685/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MLSERVICESERVICE_WSDL_LOCATION = url;
        MLSERVICESERVICE_EXCEPTION = e;
    }

    public MLServiceService() {
        super(__getWsdlLocation(), MLSERVICESERVICE_QNAME);
    }

    public MLServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MLSERVICESERVICE_QNAME, features);
    }

    public MLServiceService(URL wsdlLocation) {
        super(wsdlLocation, MLSERVICESERVICE_QNAME);
    }

    public MLServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MLSERVICESERVICE_QNAME, features);
    }

    public MLServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MLServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MLWS
     */
    @WebEndpoint(name = "MLWSPort")
    public MLWS getMLWSPort() {
        return super.getPort(new QName("http://services/", "MLWSPort"), MLWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MLWS
     */
    @WebEndpoint(name = "MLWSPort")
    public MLWS getMLWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services/", "MLWSPort"), MLWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MLSERVICESERVICE_EXCEPTION!= null) {
            throw MLSERVICESERVICE_EXCEPTION;
        }
        return MLSERVICESERVICE_WSDL_LOCATION;
    }

}
