
package services;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import net.java.dev.jaxb.array.DoubleArray;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MLWS", targetNamespace = "http://services/")
@XmlSeeAlso({
    net.java.dev.jaxb.array.ObjectFactory.class,
    services.ObjectFactory.class
})
public interface MLWS {


    /**
     * 
     * @return
     *     returns java.util.List<services.CompteDataScience>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getComptes", targetNamespace = "http://services/", className = "services.GetComptes")
    @ResponseWrapper(localName = "getComptesResponse", targetNamespace = "http://services/", className = "services.GetComptesResponse")
    @Action(input = "http://services/MLWS/getComptesRequest", output = "http://services/MLWS/getComptesResponse")
    public List<CompteDataScience> getComptes();

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMoyenne", targetNamespace = "http://services/", className = "services.GetMoyenne")
    @ResponseWrapper(localName = "getMoyenneResponse", targetNamespace = "http://services/", className = "services.GetMoyenneResponse")
    @Action(input = "http://services/MLWS/getMoyenneRequest", output = "http://services/MLWS/getMoyenneResponse")
    public double getMoyenne(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Double> arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<net.java.dev.jaxb.array.DoubleArray>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calculKMoyen", targetNamespace = "http://services/", className = "services.CalculKMoyen")
    @ResponseWrapper(localName = "calculKMoyenResponse", targetNamespace = "http://services/", className = "services.CalculKMoyenResponse")
    @Action(input = "http://services/MLWS/calculKMoyenRequest", output = "http://services/MLWS/calculKMoyenResponse")
    public List<DoubleArray> calculKMoyen(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
